In [33]:
#A script for cleaning the data for the steam project
import pandas as pd
import ast

#load data, and drop duplicates/unnamed games
df = pd.read_csv("gameDataUnfiltered.csv")
df.head()
df = df.drop_duplicates()
df = df.dropna(subset="Title")

In [34]:
df.head()

,Title,Original Price,Discounted Price,Release Date,Link,Game Description,Recent Reviews Summary,All Reviews Summary,Recent Reviews Number,All Reviews Number,Developer,Publisher,Supported Languages,Popular Tags,Game Features,Minimum Requirements
0,Baldur's Gate 3,$29.99,$29.99,"3 Aug, 2023",https://store.steampowered.com/app/1086940/Bal...,"Baldur’s Gate 3 is a story-rich, party-based R...",Overwhelmingly Positive,Very Positive,"- 96% of the 128,900 user reviews in the last ...","- 94% of the 188,617 user reviews for this gam...",Larian Studios,Larian Studios,"['English', 'French', 'German', 'Spanish - Spa...","['RPG', 'Choices Matter', 'Character Customiza...","['Single-player', 'Online Co-op', 'LAN Co-op',...",Requires a 64-bit processor and operating syst...
1,Counter-Strike: Global Offensive,$14.99,$14.99,"21 Aug, 2012",https://store.steampowered.com/app/730/Counter...,Counter-Strike: Global Offensive (CS: GO) expa...,Very Positive,Very Positive,"- 89% of the 75,284 user reviews in the last 3...","- 88% of the 7,428,921 user reviews for this g...","Valve, Hidden Path Entertainment",Valve,"['English', 'Czech', 'Danish', 'Dutch', 'Finni...","['FPS', 'Shooter', 'Multiplayer', 'Competitive...","['Steam Achievements', 'Full controller suppor...",OS: | Windows® 7/Vista/XP | Processor: | Int...
2,Apex Legends™,Free,Free,"4 Nov, 2020",https://store.steampowered.com/app/1172470/Ape...,"Apex Legends is the award-winning, free-to-pla...",Mixed,Very Positive,"- 65% of the 18,581 user reviews in the last 3...","- 80% of the 701,597 user reviews for this gam...",Respawn Entertainment,Electronic Arts,"['English', 'French', 'Italian', 'German', 'Sp...","['Free to Play', 'Multiplayer', 'Battle Royale...","['Online PvP', 'Online Co-op', 'Steam Achievem...",Requires a 64-bit processor and operating syst...
3,Forza Horizon 5,$34.78,$17.39,"8 Nov, 2021",https://store.steampowered.com/app/1551360/For...,Your Ultimate Horizon Adventure awaits! Explor...,Very Positive,Very Positive,"- 87% of the 4,120 user reviews in the last 30...","- 88% of the 123,162 user reviews for this gam...",Playground Games,Xbox Game Studios,"['English', 'French', 'Italian', 'German', 'Sp...","['Racing', 'Open World', 'Driving', 'Multiplay...","['Single-player', 'Online PvP', 'Online Co-op'...",Requires a 64-bit processor and operating syst...
4,Call of Duty®,Free,Free,"27 Oct, 2022",https://store.steampowered.com/app/1938090/Cal...,"Welcome to Call of Duty® HQ, the home of Call ...",Mixed,Mixed,"- 49% of the 8,257 user reviews in the last 30...","- 57% of the 236,876 user reviews for this gam...","Infinity Ward, Raven Software, Beenox, Treyarc...",Activision,"['English', 'French', 'Italian', 'German', 'Sp...","['FPS', 'Multiplayer', 'Shooter', 'Action', 'S...","['Single-player', 'Online PvP', 'Online Co-op'...",Requires a 64-bit processor and operating syst...

In [ ]:
#In the columns below, they are originally stored as a string formated like "[x, y, z]"
#We will turn this format of "[x, y, z]" into "x, y, z", which will help with normalization later

df["Supported Languages"] = df["Supported Languages"].apply(ast.literal_eval)
df["Supported Languages"] = df["Supported Languages"].apply(
    lambda x: ", ".join(x)
)

df["Popular Tags"] = df["Popular Tags"].apply(ast.literal_eval)
df["Popular Tags"] = df["Popular Tags"].apply(
    lambda x: ", ".join(x)
)

df["Game Features"] = df["Game Features"].apply(ast.literal_eval)
df["Game Features"] = df["Game Features"].apply(
    lambda x: ", ".join(x)
)

SyntaxError: invalid syntax (<unknown>, line 1)

In [36]:
#Pick the columns that I want to keep
df = df[[
    "Title",
    "Original Price",
    "Release Date",
    "Link",
    "All Reviews Number",
    "Developer",
    "Supported Languages",
    "Popular Tags",
    "Game Features"
    ]]

#Get rid of the dollar sign in the price column, and convert Free -> 0.00
df["Original Price"] = df["Original Price"].str.replace("$", "", regex=False)
df["Original Price"] = df["Original Price"].replace("Free", "0.00")
df["Original Price"] = pd.to_numeric(df["Original Price"], errors="coerce")

df.head()

,Title,Original Price,Release Date,Link,All Reviews Number,Developer,Supported Languages,Popular Tags,Game Features
0,Baldur's Gate 3,29.99,"3 Aug, 2023",https://store.steampowered.com/app/1086940/Bal...,"- 94% of the 188,617 user reviews for this gam...",Larian Studios,"English, French, German, Spanish - Spain, Poli...","RPG, Choices Matter, Character Customization, ...","Single-player, Online Co-op, LAN Co-op, Steam ..."
1,Counter-Strike: Global Offensive,14.99,"21 Aug, 2012",https://store.steampowered.com/app/730/Counter...,"- 88% of the 7,428,921 user reviews for this g...","Valve, Hidden Path Entertainment","English, Czech, Danish, Dutch, Finnish, French...","FPS, Shooter, Multiplayer, Competitive, Action...","Steam Achievements, Full controller support, S..."
2,Apex Legends™,0.00,"4 Nov, 2020",https://store.steampowered.com/app/1172470/Ape...,"- 80% of the 701,597 user reviews for this gam...",Respawn Entertainment,"English, French, Italian, German, Spanish - Sp...","Free to Play, Multiplayer, Battle Royale, Shoo...","Online PvP, Online Co-op, Steam Achievements, ..."
3,Forza Horizon 5,34.78,"8 Nov, 2021",https://store.steampowered.com/app/1551360/For...,"- 88% of the 123,162 user reviews for this gam...",Playground Games,"English, French, Italian, German, Spanish - Sp...","Racing, Open World, Driving, Multiplayer, Auto...","Single-player, Online PvP, Online Co-op, Cross..."
4,Call of Duty®,0.00,"27 Oct, 2022",https://store.steampowered.com/app/1938090/Cal...,"- 57% of the 236,876 user reviews for this gam...","Infinity Ward, Raven Software, Beenox, Treyarc...","English, French, Italian, German, Spanish - Sp...","FPS, Multiplayer, Shooter, Action, Singleplaye...","Single-player, Online PvP, Online Co-op, Cross..."

In [37]:
df.info()
df.shape
df.columns

<class 'pandas.core.frame.DataFrame'>
Index: 71699 entries, 0 to 71699
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Title                71699 non-null  object
 1   Original Price       71683 non-null  float64
 2   Release Date         71569 non-null  object
 3   Link                 71699 non-null  object
 4   All Reviews Number   5371 non-null   object
 5   Developer            71479 non-null  object
 6   Supported Languages  71699 non-null  object
 7   Popular Tags         71699 non-null  object
 8   Game Features        71699 non-null  object
dtypes: float64(1), object(8)
memory usage: 5.5+ MB

Index(['Title', 'Original Price', 'Release Date', 'Link', 'All Reviews Number',
       'Developer', 'Supported Languages', 'Popular Tags', 'Game Features'],
      dtype='object')

In [38]:
df.head()

,Title,Original Price,Release Date,Link,All Reviews Number,Developer,Supported Languages,Popular Tags,Game Features
0,Baldur's Gate 3,29.99,"3 Aug, 2023",https://store.steampowered.com/app/1086940/Bal...,"- 94% of the 188,617 user reviews for this gam...",Larian Studios,"English, French, German, Spanish - Spain, Poli...","RPG, Choices Matter, Character Customization, ...","Single-player, Online Co-op, LAN Co-op, Steam ..."
1,Counter-Strike: Global Offensive,14.99,"21 Aug, 2012",https://store.steampowered.com/app/730/Counter...,"- 88% of the 7,428,921 user reviews for this g...","Valve, Hidden Path Entertainment","English, Czech, Danish, Dutch, Finnish, French...","FPS, Shooter, Multiplayer, Competitive, Action...","Steam Achievements, Full controller support, S..."
2,Apex Legends™,0.00,"4 Nov, 2020",https://store.steampowered.com/app/1172470/Ape...,"- 80% of the 701,597 user reviews for this gam...",Respawn Entertainment,"English, French, Italian, German, Spanish - Sp...","Free to Play, Multiplayer, Battle Royale, Shoo...","Online PvP, Online Co-op, Steam Achievements, ..."
3,Forza Horizon 5,34.78,"8 Nov, 2021",https://store.steampowered.com/app/1551360/For...,"- 88% of the 123,162 user reviews for this gam...",Playground Games,"English, French, Italian, German, Spanish - Sp...","Racing, Open World, Driving, Multiplayer, Auto...","Single-player, Online PvP, Online Co-op, Cross..."
4,Call of Duty®,0.00,"27 Oct, 2022",https://store.steampowered.com/app/1938090/Cal...,"- 57% of the 236,876 user reviews for this gam...","Infinity Ward, Raven Software, Beenox, Treyarc...","English, French, Italian, German, Spanish - Sp...","FPS, Multiplayer, Shooter, Action, Singleplaye...","Single-player, Online PvP, Online Co-op, Cross..."